services:
  spacex-mysql:
    image: mysql:8.0
    container_name: spacex-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spacex_metadata
    volumes:
      - ./.data/mysql:/var/lib/mysql

  spacex-mongodb:
    image: mongo:latest
    container_name: spacex-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./.data/mongodb:/data/db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: spacex-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: spacex-mysql
      MYSQL_ROOT_PASSWORD: root